### ISSUE TITLE
SERVICE:  Additional catalog source (Analysis)

### ISSUE THREAD

**Issue by jsoftgem** [great-design-and-systems/cataloguing-service#1]
Currently we're using library of congress SRU to retrieve catalog data.

Please research on other sources like OPAC and put their links on the comment.

**Comment by analynf** [comment]
https://www.loc.gov/standards/sru/resources/listOfServers.html

**Comment by analynf** [comment]
Added:
https://na01.alma.exlibrisgroup.com/view/sru/01ALLIANCE_NETWORK
